const ActionTypes = {
  USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

  USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
  USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

  USER_LOGOUT: 'USER_LOGOUT',

  // Product
  PRODUCT_FETCH_REQUEST: 'PRODUCT_FETCH_REQUEST',
  PRODUCT_FETCH_SUCCESS: 'PRODUCT_FETCH_SUCCESS',
  PRODUCT_FETCH_FAILURE: 'PRODUCT_FETCH_FAILURE',

  // Cart
  ADD_TO_CART: 'ADD_TO_CART',
  INCREASE_QUANTITY_ORDER_PRODUCT: 'INCREASE_QUANTITY_ORDER_PRODUCT',
  DECREASE_QUANTITY_ORDER_PRODUCT: 'DECREASE_QUANTITY_ORDER_PRODUCT'
};

export default ActionTypes;